[package]
name = "lg_prime_factor_03"
version = "0.1.0"
authors = ["Vigneshkumar <Vigneshkumar.Sadasivam@in.bosch.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
